# Generated by Django 3.0.2 on 2020-02-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200201_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
